[env:esp32dev]
platform = espressif32@7.1.3
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
    -DWIFI_SSID=\"${sysenv.WIFI_SSID}\"
    -DWIFI_PASS=\"${sysenv.WIFI_PASS}\"
    -DGATEWAY_URL=\"${sysenv.GATEWAY_URL}\"
lib_deps =
    bblanchon/ArduinoJson@^7
